#!/usr/bin/env ruby
require 'pp'
require 'optparse'
require 'ostruct'
require_relative "testlib"

options = OpenStruct.new
options.sim = "incisive" 
options.output = "test_randomize.dat"

OptionParser.new do |opts|
  opts.banner = "Usage: run_test_randomize [-s <simulator=incisie>]"

  opts.on("-s", "--sim simulator",
          "Name of simulator to use") do |sim|
    options.sim = sim
  end

  opts.on("-o", "--output filename", "Output testname") do |name|
    options.output = name
  end

end.parse(ARGV)
sim = options.sim
output = options.output

benchmark = {}

n = 1
3.times do
  benchmark[n] = runtest(n: n, sim: sim, test: "test_randomize")[:time]
  n = n * 10
end

File.open(output, "w") do |fh|
  fh.puts "SizeOfTable,CpuTime(sec)"
  benchmark.each do |key, value|
    fh.puts "#{key}, #{value}"
  end
end

