#!/usr/bin/env ruby
require 'pp'
require 'optparse'
require 'ostruct'
require_relative "testlib"

test = "srm_test_randomize"

options = OpenStruct.new
options.sim = "incisive" 
options.output = "#{test}.dat"

OptionParser.new do |opts|
  opts.banner = "Usage: run_srm_test_randomize [-s <simulator=incisie>]"

  opts.on("-s", "--sim simulator",
          "Name of simulator to use") do |sim|
    options.sim = sim
  end

  opts.on("-o", "--output filename", "Output testname") do |name|
    options.output = name
  end

end.parse(ARGV)
sim = options.sim
output = options.output

benchmark = {}

n = 1
4.times do
  benchmark[n] = runtest(n: n, sim: sim, test: test, srm: 1)[:time]
  n = n * 10
end

2.upto(5) do |i|
  n = 1000 * i 
  benchmark[n] = runtest(n: n, sim: sim, test: test)[:time]
end

1.upto(3) do |i|
  n = 10000 * i 
  benchmark[n] = runtest(n: n, sim: sim, test: test)[:time]
end

File.open(output, "w") do |fh|
  fh.puts "SizeOfTable,CpuTime(sec)"
  benchmark.each do |key, value|
    fh.puts "#{key}, #{value}"
  end
end

