#!/usr/bin/env ruby
require 'pp'
require 'optparse'
require 'ostruct'
require_relative "testlib"

options = OpenStruct.new
options.sim = "incisive" 
options.output = "srm_tutorial_9.dat"

OptionParser.new do |opts|
  opts.banner = "Usage: runsim [-s <simulator=incisie>]"

  opts.on("-s", "--sim simulator",
          "Name of simulator to use") do |sim|
    options.sim = sim
  end

  opts.on("-o", "--output filename", "Output testname") do |name|
    options.output = name
  end

end.parse(ARGV)
sim = options.sim
output = options.output

benchmark = {}

n = 1
6.times do
  benchmark[n] = runtest(n: n, sim: sim, test: "srm_tutorial_9", srm: 1)[:mem]
  n = n * 10
end

#Generate 100K to 500
2.upto(5) do |i|
  n = 100000 * i
  benchmark[n] = runtest(n: n, sim: sim, test: "tutorial_9")[:mem]
end

File.open(output, "w") do |fh|
  fh.puts "NumberOfReg,MemoryMB"
  benchmark.each do |key, value|
    fh.puts "#{key}, #{value}"
  end
end

